---

## Disable AAF? (To log in using Keystone auth directly)
disable_aaf: False

## Verbosity Options
debug: True
verbose: True

# Name of the virtual env to deploy into
horizon_venv_path: /opt/horizon

# Set this to enable or disable installing in a venv
horizon_venv_enabled: True

horizon_developer_mode: True
horizon_developer_constraints:
  - 'git+https://github.com/NeCTAR-RC/django_openstack_auth.git@nectar/liberty#egg=openstack_auth'
  - 'git+https://github.com/NeCTAR-RC/horizon.git@nectar/queens#egg=horizon'
  - 'git+https://github.com/openstack/murano-pkg-check.git@47f7379e5e91eac2ba9ede6645cb56ff305d2c0c#egg=murano-pkg-check' # https://bugs.launchpad.net/murano/+bug/1653060
  - 'git+https://github.com/openstack/murano-dashboard.git@stable/queens#egg=muranodashboard'

## DB info (set to django.db.backends.mysql or django.db.backends.sqlite3)
horizon_database_engine: django.db.backends.mysql

## DB info for MySQL
mysql_install_phpmyadmin: True
mysql_root_user: root
mysql_root_password: myrootpassword
horizon_mysql_host: localhost
horizon_mysql_user: horizon
horizon_mysql_password: mydbpassword
horizon_mysql_database: dashboard1

## DB info for SQLite and other non-MySQL
# horizon_database_name: "{{ horizon_system_user_home }}/dashboard.sqlite3"
# horizon_database_address: localhost
# horizon_database_user: horizon
# horizon_database_password: mydbpassword

## Session configuration
horizon_session_timeout: 21600  # 6 hours

## Dashboard customisations
horizon_site_name: Melbourne Research Cloud

nectar_dashboard_repo: 'https://github.com/UoM-ResPlat-DevOps/uom-cloud-dashboard.git'
nectar_dashboard_path: /opt/uom-cloud-dashboard
nectar_dashboard_version: nectar/queens-develop

nectar_dashboard_enabled:
  - _40_disable_change_password.py
  - _40_disable_identity.py
  - _50_reset_password_panel.py
  - _70_allocations.py
  - _9000_disable_dns_reversedns.py
  - _9000_disable_trove_clusters.py
  - _9000_disable_volume_cg.py
  - _9000_disable_volume_cg_snapshots.py
  - _9001_users_add_panel_to_group.py
  - _9900_disable_share_networks.py
  - _9900_users_add_panel_group.py
nectar_dashboard_disabled:
  - _80_manila_project_add_share_panel_group.py

## Allocations customisations
allocations_project_prefix: unimelb-
allocations_email_from_address: "My Research Cloud <support@researchcloud.tld>"
# The following three vars must be lists
allocations_email_cc:
  - admin@researchcloud.tld
allocations_email_bcc: []
allocations_email_reply_to:
  - support@researchcloud.tld

# Required for using the NeCTAR allocations client
allocations_keystone_username: yourname@institution.tld
allocations_keystone_password: yourpassword
allocations_keystone_project_name: yourproject
allocations_nectar_admin_role: AllocationAdmin
allocations_nectar_client_vers: '1'
allocations_nectar_client_source: uom

## Email settings
# To email to console: django.core.mail.backends.console.EmailBackend
horizon_email_backend: django.core.mail.backends.smtp.EmailBackend
horizon_email_host: smtp.unimelb.edu.au
horizon_email_port: 25
# Keep the user and password commented out if they're not needed:
# horizon_email_user
# horizon_email_password

# UoM nav support links
uom_navbar_support_links:
  - text: Submit a ticket
    icon: fa-ticket
    url: https://unimelb.service-now.com/research
  - '-'
  - text: Research Platform Services
    icon: fa-external-link
    url: https://research.unimelb.edu.au/infrastructure/research-platform-services

## System info
horizon_system_user_name: horizon
horizon_system_group_name: www-data
horizon_system_shell: /bin/false
horizon_system_comment: horizon system user
horizon_system_user_home: "/var/lib/{{ horizon_system_user_name }}"

# Service end-points
horizon_rcshibboleth_url: 'https://accounts.test.rc.nectar.org.au/rcshibboleth'
horizon_murano_enabled: True
horizon_murano_api_url: 'https://murano.test.rc.nectar.org.au:8082'

## Service Type and Data
horizon_service_region: RegionOne
horizon_service_name: horizon

## Horizon Help URL Path
horizon_help_url: 'https://support.ehelp.edu.au/'

horizon_endpoint_type: publicURL

## Installation directories
horizon_bin: "{{ horizon_venv_path }}/bin"
horizon_venv_lib_dir: "{{ horizon_bin | dirname }}/lib/python2.7/dist-packages"
horizon_non_venv_lib_dir: "/usr/local/lib/python2.7/dist-packages"
horizon_lib_dir: "{{ (horizon_venv_enabled | bool) | ternary(horizon_venv_lib_dir, horizon_non_venv_lib_dir) }}"
horizon_lib_wsgi_file: "{{ horizon_lib_dir }}/openstack_dashboard/wsgi/django.wsgi"

horizon_server_name: researchcloud.tld
horizon_apache_servertokens: "Prod"
horizon_apache_serversignature: "Off"
horizon_log_level: debug
horizon_apache_custom_log_format: combined
horizon_dropdown_max_items: 30
horizon_time_zone: "Australia/Melbourne"
horizon_enforce_password_check: False
horizon_disable_password_reveal: False
horizon_enable_password_retrieve: False
# If nova_libvirt_inject_password is set to True, then this can also be enabled:
horizon_can_set_password: False
horizon_enable_cinder_backup: False

# If the following variables are unset in user_variables, the value set will be half the number of available VCPUs
# horizon_wsgi_processes: 4
# horizon_wsgi_threads: 4

## Horizon SSL
horizon_ssl_enabled: False
horizon_ssl_cert: /etc/ssl/certs/horizon.pem
horizon_ssl_key: /etc/ssl/private/horizon.key
horizon_ssl_ca_cert: /etc/ssl/certs/horizon-ca.pem

horizon_ssl_protocol: "ALL -SSLv2 -SSLv3"
horizon_ssl_cipher_suite: "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
# if using a self-signed certificate, set this to true to regenerate it
horizon_ssl_self_signed_regen: False
horizon_ssl_self_signed_subject: "/C=AU/ST=Victoria/L=Melbourne/O=NeCTAR/CN={{ horizon_server_name }}/subjectAltName=IP.1={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

## Horizon's keystone endpoint settings
horizon_keystone_host: "keystone.test.rc.nectar.org.au"
horizon_keystone_endpoint: "https://{{ horizon_keystone_host }}:5000/v3"

## Horizon Multi-Domain Support
# these variables should only be changed if horizon_keystone_endpoint is a Keystone v3 API endpoint
horizon_keystone_multidomain_support: False
horizon_keystone_default_domain: Default

### Set the cacert pem for Keystone if you'd like Horizon to verify it.
# horizon_cacert_pem: /path/to/cacert.pem

## alternatively, you can set horizon to turn off ssl verification for Keystone
horizon_ssl_no_verify: True

## The role which Horizon should use as a default for users
horizon_default_role_name: Member

## Horizon secret key
#horizon_secret_key: '{{ lookup("password", "credentials/horizon/secret_key length=32") }}'
horizon_secret_key: random_hash

## Launch instance
horizon_launch_instance_legacy: True
horizon_launch_instance_ng: False

## Neutron features to enable
horizon_enable_neutron_lbaas: False

## Swift
horizon_swift_file_transfer_chunk_size: 524288

# For blacklisting certain Nova extensions uncomment this configuration,
# and add necessary list items.
# horizon_nova_extensions_blacklist:
#   - "SimpleTenantUsage"

memcached_servers: '127.0.0.1:11211'

horizon_webroot: /

horizon_listen_ports:
  - "80"
  - "443"

# horizon packages that must be installed before anything else
horizon_requires_apt_packages:
  - build-essential
  - python-dev

horizon_apt_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi
  - libssl-dev
  - libxslt1.1
  - openssl
  - libsqlite3-dev
  - git

# horizon packages that must be installed before anything else
horizon_requires_pip_packages:
  - virtualenv
  - virtualenv-tools
  - python-keystoneclient # Keystoneclient needed to OSA keystone lib
  - httplib2

horizon_pip_packages:
  - django-appconf
  - greenlet
  - 'git+https://github.com/NeCTAR-RC/django_openstack_auth.git@nectar/liberty#egg=openstack_auth'
  - 'git+https://github.com/NeCTAR-RC/horizon.git@nectar/queens#egg=horizon'
  - keystonemiddleware
  - PyMySQL
  - pysqlite
  - ply
  - pycrypto
  - python-memcached
  - 'git+https://github.com/openstack/murano-pkg-check.git@47f7379e5e91eac2ba9ede6645cb56ff305d2c0c#egg=murano-pkg-check' # https://bugs.launchpad.net/murano/+bug/1653060
  - 'git+https://github.com/openstack/murano-dashboard.git@stable/queens#egg=muranodashboard'
  - 'git+https://github.com/openstack/trove-dashboard.git@stable/queens#egg=trove_dashboard'
