---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# sudo apt install phpmyadmin php-mbstring php-gettext
# sudo phpenmod mbstring

- name: Install MySQL packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - mysql-server
    - python-mysqldb
    - libmysqlclient-dev
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Copy MySQL root credentials as .my.cnf file
  template:
    src: root.cnf.j2
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - "~/.my.cnf"
    - "/home/ubuntu/.my.cnf"
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: "{{ mysql_root_user }}"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
  with_items:
    - "{{ horizon_mysql_host }}"
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Remove anonymous users from database
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ horizon_mysql_host }}"
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
  notify:
    - Restart MySQL
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Create DB for service
  mysql_db:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ horizon_mysql_host }}"
    name: "{{ horizon_mysql_database }}"
    state: "present"
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ horizon_mysql_host }}"
    name: "{{ horizon_mysql_user }}"
    password: "{{ horizon_mysql_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ horizon_mysql_database }}.*:ALL"
  with_items:
    - "localhost"
    - "%"
  when: horizon_database_engine == "django.db.backends.mysql"
  tags:
    - horizon-db-setup

- name: Register DB session cleanup cron
  cron:
    name: "Clear out expired sessions"
    minute: "{{ 58 | random(start=2) }}"
    hour: 21
    job: "{{ horizon_bin }}/horizon-manage.py clearsessions"
    user: "{{ horizon_system_user_name }}"
    state: present
  tags:
    - horizon-db-setup

- name: Install phpmyadmin packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - phpmyadmin
    - php-mbstring
    - php-gettext
  when: (horizon_database_engine == "django.db.backends.mysql") and mysql_install_phpmyadmin
  tags:
    - horizon-db-setup

- name: Enable mbstring for phpmyadmin (works with Debian only)
  command: "phpenmod mbstring"
  when: (horizon_database_engine == "django.db.backends.mysql") and mysql_install_phpmyadmin
  tags:
    - horizon-db-setup
